### ISSUE TITLE
Impact of access restrictions

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#10]
If an implementation limits the access to a subset of the operations for some users (or if the server implements even more fine-grained access), it may no longer be possible for such a user to de-reference all links, including relationships between features. Does this require a discussion? Or more?

**Comment by cmheazel** [comment]
Some cases we need to consider are:
1) An implementation limits access to specific operations
2) An implementation limits access to specific Feature Collections, Features, and/or Feature Attributes
3) An implementation limits access to specific Feature Collections --- by specific operations
4) An implementation limits access to knowledge that a resource exists
5) An implementation may required additional credentials to access a resource

These restrictions may be based on user, role, credentials, or in some cases location of the user. 
Credentials include access permissions, licenses, and payment of a required fee.

**Comment by rcoup** [comment]
Maybe some guidance to use the most appropriate [4xx HTTP error codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors)

eg.

- 401 Unauthorized — where an anonymous request isn't allowed but an authorised one may be. (case 5)
- 403 Forbidden — where the user doesn't have access to the data/operation. (cases 1, 2, 3)
- 404 Not Found — where the data shouldn't be visible for the requesting user. (case 4; maybe case 1 if the operation isn't available _at all_)
- 429 Too Many Requests — a rate limit has been exceeded

Though currently [9.3. Exceptions](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#exceptions) only lists 400 Bad Request as an appropriate response, which seems limiting.

Consistent error response formats would certainly help. AFAICT the current response is 
```
{
  code: "forbidden",
  description: "you don't have access to this data or operation"
}
```

Predefined exception codes could be helpful? eg. Mapping the above to specific code strings: "unauthorized", "forbidden", "not-found", "too-many-requests".

**Comment by pvretano** [comment]
We've imlemented everything that Chuck is describing including location based access control and I can tell you that it is way out of scope for a simple core.  We should try to limit our discussion to the simplest cases possible (e.g. access based on operation and collection).  Regardless, I suspect that the best we might be able to do in a simple core is talk about the topic in a non-normative way.

**Comment by cmheazel** [comment]
Agree that it is out of scope for a simple core.  However, we don't want to do anything in this simple core which precludes the more complex cases.  So it helps to have some understanding of what those cases could require.

**Comment by cportele** [comment]
The idea behind the comment was that even if the core does not specify requirements for how to deal with access control etc. this does not preclude that a server will respond with, for example, 403, 404, etc. as it has been pointed out and we probably should have a discussion and maybe permissions in the text.

**Comment by rcoup** [comment]
My reckons:
- don't specify how to do it in core. 
- recommend to use appropriate HTTP response codes for authorization-related responses
- recommend to use the WFS error format for those responses (as a minimum, can always add additional attributes/details)
- prohibit returning 2XX responses that are errors (ala some existing OGC specs)

**Comment by cportele** [comment]
The current approach is stronger than this. 

https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_http_1_1 requires that the appropriate http status codes have to be returned by the server (not just recommended). My point was whether we should clarify in a note that clients have to be prepared to receive authorization-related status codes.

https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#exceptions then adds requirements for some well-defined error situations. This needs more detail and could also be moved back to the core.

**Comment by rcoup** [comment]
https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#exceptions
> For error situations that are the result of a bad request by the client, error code "400" SHALL be used.

Arguably nearly everything authorisation-related is a client error (either you asked for something you shouldn't, or you haven't provided enough proof), so this should be reworded I think? I read it as "only 400 is allowed".

Maybe
> For error situations that are the result of a bad request by the client, the appropriate 400-series HTTP error code SHALL be used.

**Comment by cmheazel** [comment]
I'll contribute a writeup applying the principles we developed for the OWS Security standard to OpenAPI.  That will allow the client and server to negotiate authorization protocols.  Another lesson we learned is not to restrict the HTTP error codes.  What made sense when we wrote specs in 1999 does not make sense today.

**Comment by cportele** [comment]
@rcoup - Agreed, this should be changed as you propose. The idea off the "400" requirement was to map the errors codes from WFS 2.0 like InvalidParameterValue to HTTP status codes. But maybe we do not need to do this.

@cmheazel - Thanks.

**Comment by rcoup** [comment]
Yes, `400 Bad Request` applies to most things where query parameters or options are bad/incompatible/missing/etc, so 👍 wrt defining that. But we should enable the use of other 4xx codes for the situations (eg. authorisation) when it's appropriate.

**Comment by cportele** [comment]
Agreement on 2018-02-01: Table it for now. If we have content in the Guide (see @cmheazel's offer above), we can reference it. Testbed 14 will also look at this.

**Comment by cmheazel** [comment]
See write-up in section 10 of the GUIDE.  I think this is about as close as we can come.
