### ISSUE TITLE
Relation types in landing page

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#101]
Landing page: Can we reuse existing relation types instead of 'conformance' and 'data'?

**Comment by pvretano** [comment]
If that is the case then why have a /api at all ... or a landing page?  We can simply say that hitting the root gets you the service description in the representation requested.  Is there a MIME type for open api documents?

**Comment by cmheazel** [comment]
The landing pages I have seen have been largely geared toward a human audience.  A nice starting point for follow-your-nose navigation. Not so good if your user is a software analytic.  Analytics will want access to a machine readable description of the API such as the OpenAPI document.  A human user may not look at the OpenAPI document at all.  They may just want to follow the links.
So it gets down to your user scenario.
And this comment may have nothing to do with the original issue and I apologize if I have dragged us off on a tangent.

**Comment by cportele** [comment]
The landing page is for humans.

Humans will go from `/` to `/collections` (unless `/` already includes the information from the collections metadata information) and from there to the data. If they are developers they may also follow the `/api` link. Humans that are not developers will in general not be happy with the `/api` response, so it makes sense the have `/` as well. We discussed this in the context of #64.

Machines may navigate towards the data (follow the `/collections` link), if the want to use the hypermedia characteristics and do not care about WFS or OpenAPI. If they care about OpenAPI, they will go to `/api` (and to an OpenAPI library I would directly pass the `/api` link). WFS clients will also look at `/conformance`.

**Comment by cportele** [comment]
Keep the relation types and consider submitting a registration request after approval. A stable spec reference is a requirement for registration. 

What we probably should do now is to define link relation types created by us more formally in the document.

**Comment by cportele** [comment]
06-MAY-2019 Conference call: Add a table with all link relations and reference their definitions (for example, "self", "alternate", "next", etc.) and define the new ones (for example, "conformance"). Once we have the table, we should also review the use of relation types again.
