### ISSUE TITLE
Link to dataset metadata?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#102]
Add recommendation about a link to the dataset metadata (for example, in DCAT)? 

Which link relation type?

**Comment by jvanulde** [comment]
Perhaps this might be helpful: https://www.w3.org/TR/cooluris/#distinguishing. We could also consider the `describedby` relation although I don't know if that's appropriate in this case.

**Comment by jvanulde** [comment]
https://www.iana.org/assignments/link-relations/link-relations.xhtml

**Comment by jvanulde** [comment]
Would the `about` relation be in the metadata pointing to the collection/feature and the `describedby` relation in the collection/feature representation pointing to the metadata?

**Comment by pvretano** [comment]
Hmm ... Actually "about" may not be the right rel. to use in this case (if I understand RFC6903) correctly.
Maybe describe/describedBy is better suited in this case ...

- collection/feature-----(describedBy)-----> metadata
- metadata -----(describes)---->collection/feature

We have also been using "describedBy" to point to the schema of a collection ... that still makes sense ... right?

**Comment by cportele** [comment]
My concern with `describedby` is that it fits so many relations ("Refers to a resource providing information about the link's context"). We have used it for the schemas, feature catalogues, etc. as those describes the data. But the dataset metadata also describes the data. If we used `describedby` for all these cases then a client has to follow the links to see what it gets or hope to get more hints from the media type. Since, for example, a ISO 19139 metadata record and an XML Schema document would likely have both `application/xml` as the media type since W3C/OGC never registered media types for these XML document types, this seems quite fragile. But I am not aware of anything better unless we invent our own link relations...

**Comment by pvgenuchten** [comment]
What's the status of this, having the option to link seems very relevant, choosing the appropriate link type should not prevent us to add it.

**Comment by cportele** [comment]
@pvgenuchten - The issue will be discussed and resolved in the coming weeks (before August). This applies to all issues associated with the [milestone for the "Second Draft Release"](https://github.com/opengeospatial/WFS_FES/milestone/2).

**Comment by cportele** [comment]
06-MAY-2019 Conference call: Based on the decision in #160 we do not need to worry about this in the Core.

**Comment by cportele** [comment]
Conference call, 3 June 2019: Closing this issue as there was no further discussion. If new aspects are to be considered, the issue can be reopened.
