### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/WFS_FES#104]
Right now the description for WFS 3 assumes quite a bit of pre-existing knowledge about what WFS is. It'd be good to have it speak to everyone, not just those in the know.  Make the tagline be something more like 'an open standard for querying geospatial information on the web' instead of 'Repository for the work of the WFS/FES SWG'

It'd also be good to update the 'link'. Having the link be the same page you're looking at is not so helpful. https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html or a stable link to the milestone 1 draft would probably be good to have in that link - take people straight to the document (better would be a user's guide, but that doesn't exist yet).

**Comment by cportele** [comment]
I will update the repo description with the release for the 1st milestone.

**Comment by cportele** [comment]
Duh, I noticed that I do not have the rights to edit that information.

@ogcscotts - I will assign this to you as I assume that you could update the repo description.

**Comment by ogcscotts** [comment]
Isn't the repo description just the readme file? If so, I will edit according to this and Issue #106

**Comment by cportele** [comment]
No, it is the tagline and the URL at the top.

Thanks!

**Comment by cportele** [comment]
https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github

**Comment by ogcscotts** [comment]
Hah, I don't have those rights either. I'll get it changed.

**Comment by cholmes** [comment]
Would be good if spec editors in general have the ability to change that.

**Comment by ogcportal** [comment]
The description and URL have been updated per your request.

**Comment by cportele** [comment]
@ogcportal - Could you update the URL to https://cdn.rawgit.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html (the stable draft release)?

Also, "An open standard draft ..." in the tagline sounds a bit strange to me, but maybe it is correct English. If not maybe change to "An open draft standard ..."?

Thanks!
