### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/WFS_FES#106]
The readme for WFS 3 assumes quite a bit of pre-existing knowledge about what WFS is. It'd be good to have it speak to everyone, not just those in the know.

Some brain dump suggestions:

* FIrst paragraph should explain what a web feature service is, and why people would use the spec, and probably take the 'about' name there. 
* 'communication' section should probably explain a bit more about what the mailing lists and gitter are for - like 'jump on with any questions you have with the spec' and/or 'this is where we discuss changes / improvements.
* current 'about' should probably be titled something like 'resources' or 'getting started' with just roughly the first half of it - could use some tweaking to think about an audience who doesn't know what's going on.
* Would be good to show a couple actual requests in the first couple of paragraphs. Like show the '/collections/{collectionId}/items' pattern, or a maybe a little workflow of getting data.
* Ideally link to a server that is up to date with the draft, for people to play around with
* Should also link to openapi documents. Is there a way to stand up what http://editor.swagger.io/ gets you put in a persistent way?
* Contributing should be less about the legalities, more like 'try out implementing a service, file github issues, create extensions, etc'

I'll try to take some time to make a PR on this. I suppose it doesn't need to happen before M1 (and not sure I'll have time before then), but it'd be good to have up before we start spreading the message that M1 is ready for feedback.

**Comment by cportele** [comment]
👍 

Maybe include the [resource overview table](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#tldnr) into the readme?

Any changes to "Contributing" should be reviewed by @ogcscotts.

**Comment by cholmes** [comment]
Yeah, resource overview table could be good there. I think I'd do a 'quick start' that glosses over like the 'conformance' resource. But a bit further down it'd be good. The nice thing would be the links in to the actual document. Indeed we should be sure that the readme has lots of liberal linking in to the most relevant parts of the document. So that few have to approach the document as a whole, they can just follow the readme and it'll lead in to the information they need to know to implement.

**Comment by cholmes** [comment]
This is merged now.
