### ISSUE TITLE
Support for HEAD and OPTIONS

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#115]
Currently, the Core only requires support for the GET method.

In practice, support for HEAD and OPTIONS for all resources should be considered, too:

* HEAD is basically free to implement, but can be useful to check that a resource exists.
* OPTIONS is useful to determine the other HTTP methods supported by the resource. It is also needed for CORS preflight requests.

(This was originally raised in #105.)

**Comment by rcoup** [comment]
Definitely nice to have, but are they really _essential_ to implement in core?

**Comment by cportele** [comment]
Good point, probably you are right. Maybe we could also just mention them in an informative way to make everyone aware of them, but no add anything normative.

**Comment by pvretano** [comment]
Normative is fine until we get further feedback from TB14, etc ...

**Comment by akuckartz** [comment]
The WFS specification can and should refer to RFC 7231.

https://tools.ietf.org/html/rfc7231#section-4.3.2 states:

> The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request had been a GET, except that the payload header fields (Section 3.3) MAY be omitted.

**Comment by cportele** [comment]
15-April-2019 Teleconference: Do add requirements for HEAD / OPTIONS. Recommend that HEAD is implemented (it is also simple to support). OPTIONS is needed for CORS and we should mention it in that context.

**Comment by cportele** [comment]
resolved by #208
