### ISSUE TITLE
Behaviour of bbox and time parameters if feature does not have spatial and/or temporal properties

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/WFS_FES#121]
How should a wfs behave if a request has a spatial and/or temporal filter but the feature does not have spatial and/or temporal properties?  Should the wfs ignore the filter(s) or not?

**Comment by cportele** [comment]
15-April-2019 Teleconference: The server will ignore the query parameters for features that have no spatial or temporal properties (as proposed by #122), i.e. they match all bbox/time parameters.
