### ISSUE TITLE
Consider removing "break free" language from Overview

### ISSUE THREAD

**Issue by serich** [opengeospatial/WFS_FES#124]
Minor editorial suggestion: The 2nd paragraph in the section "The next version of WFS - an overview" (https://github.com/opengeospatial/WFS_FES/blob/master/overview.md) contains language that "The next version (WFS 3.0) is intended to break free of this legacy...". 

This language could be interpreted as meaning that WFS 2.x and other earlier versions could soon be deprecated or might otherwise become unavailable for certifiable implementation.

Perhaps this language should be reworded to be less threatening, maybe something like "The next version (WFS 3.0) is intended to provide a modern alternative to this legacy...".

**Comment by aaime** [comment]
Agreed :-)

**Comment by cportele** [comment]
resolved by #208
