### ISSUE TITLE
Deviations between XML and JSON encoding of various structures.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/WFS_FES#133]
At the moment, the XML encoding and JSON encoding of various structures deviates slightly making it difficult to use certain generation tools such as Jackson.  For example, the XML encodings use atom:links to encode links while the JSON encoding uses a similar "link" structure define the WFS 3.0 specification (because there are no OWS common encodings defined in JSON).  Similarly, the XML encoding uses the OWS Common encoding for bbox while the JSON encoding uses the bbox structure defined in WFS 3.0.
The main reason for doing this was to allow people who have already invested code building WFS 2.X to reuse some of that code for supporting WFS 3.0.
However, this raises a question!  For the XML encoding, should we try to reuse existing, familiar encodings (e.g. from OWS common) OR should we try to mirror the JSON encodings?
Also, we would like to hear from people using other languages (e.g. Python or Go) and who are implementing both XML and JSON support .

**Comment by pvretano** [comment]
It should be pointed out that JSON and XML will inevitably deviate because the feature model on GeoJSON and GML are different.

**Comment by aaime** [comment]
Another example of deviation is the spatial domains representation, array vs nested objects.

**Comment by cportele** [comment]
06-MAY-2019 Conference call: Peter will review the differences. As long as the information (in the XML) is equivalent (to the JSON) we are ok.

**Comment by cportele** [comment]
Conference call 10 June 2019: A few changes have been made by Peter directly in the master branch. The json/xml content should now be up to date and equivalent. Everyone to review until the hackathon. 

The json directory under xml should move to a parallel directory to the xml directory. @cmheazel will create a PR for moving the files and update the file references this week. It will be merged directly, this is editorial cleanup.

**Comment by cmheazel** [comment]
All examples have been moved under core/examples.  Separate directories have been created for the JSON and XML examples.  Note: none of the JSON examples are referenced from the spec and the Api.xml is also not referenced.

**Comment by cportele** [comment]
The issue has been resolved and checked, so we close the issue.
