### ISSUE TITLE
Expected behavior when multiple filtering parameters are used (e.g., bbox and time)

### ISSUE THREAD

**Issue by aaime** [opengeospatial/WFS_FES#136]
The spec says "A bbox *or* time parameter may be used to select only a subset of the features in the collection (the features that are located in the bounding box or time period)."

What if a "bbox *and* a time parameter" are used instead? With eventual extra filtering properties too?

For reference, the WFS 2.0 specification requires to throw an exception is bbox and filter are used at the same time.

**Comment by pvretano** [comment]
I think it is allowed to have any combination of bbox, time and property filtering parameters.  It does not have any text in the standard about this but I would assume that the implied logical operator in this case is AND.  Perhaps a sentence or two about this would be in order.
For what its worth, my implementation handled the bbox, time and property filtering parameters in this way.

**Comment by cportele** [comment]
Yes, that is the intention (and also our implementation).

**Comment by sampov2** [comment]
Has there been any discussion or anything in the specification about multiple accepted values for a single filter? For example a case where a user is interested in features where the property value is any of a list of 10 values. Would the user need to make a query for each value, or could the user pass multiple values as multiple parameters. I.e.

"http://..../collections/MYCOLLECTION/items?bbox=10,10,20,20&param=value1&param=value2&...param=value10"

This would mean "(bbox INTERSECTS [10,10,20,20]) AND (param = 'value1' OR param = 'value2' ... OR param = 'value10')"

What do you think?

**Comment by pvretano** [comment]
@sampov2  There are several related work items currently in OGC Testbed 14. One is the Complex Feature Handling Engineering Report.  There is also the Next Generation Web APIs engineering report.  Testbed 14 is coming to a close now so both reports should be available publicly soon ... although I think the Complex Feature Handling ER is already publicly available in github somewhere.   The one that is closest to what you propose is the use of CQL like this: http://.../collections/MYCOLLECTION/items?filter=(bbox INTERSECTS [10,10,20,20]) AND (param = v1 OR param = v2 ... OR param = v10)&filterLanguage=CQL...

**Comment by serich** [comment]
@sampov2 The public GitHub repo for this ER is at https://github.com/opengeospatial/D040-Complex_Feature_Handling_Engineering_Report. If you scroll down to the bottom of the README.md file, there's a "Link to the current draft...". For convenience, the latest link is https://rawgit.com/opengeospatial/D040-Complex_Feature_Handling_Engineering_Report/master/18-021.html.
