### ISSUE TITLE
Add section "Security Considerations"

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#137]
It is good practice to provide security related guidance in a standard in a section "Security Considerations". Add such a section and include results from implementation experiences including from OGC Testbed 14.

(Raised by the OGC Architecture Board, OAB)

**Comment by cmheazel** [comment]
First draft has been added as Section 11

**Comment by cportele** [comment]
@cmheazel - instead of commiting this to the master branch, could you move this to a separate branch and create a pull request? Thanks!

**Comment by cmheazel** [comment]
Have backed out section 11 and created a Security-Updates branch.  I will try to weave together all of the security related parts of the spec prior to issuing a pull request.
