### ISSUE TITLE
Necessity of the link to collection in Feature response

### ISSUE THREAD

**Issue by jampukka** [opengeospatial/WFS_FES#138]
What is the idea behind the link to the collection in Feature response?
This one:

> Link: <http://data.example.org/collections/buildings/items.json>; rel="collection"; type="application/geo+json"

In the requirement it states that this is "a link to the feature collection that contains this feature". There's a high chance the feature won't appear in the response one gets by following the link. Can this be confusing? I'm having hard time seeing the benefit of the requirement.

**Comment by cportele** [comment]
13-MAY-2019 Conference call: The link is helpful as you can get to the collection and potentially apply other queries/filters. Keep the link.
