### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by geons** [opengeospatial/WFS_FES#144]
On p37 of OGC Web Feature Service 3.0: Part 1 - Core  (actually p41 of the pdf doc)
Example 6. A date-time
>February 12, 2018, 23:20:52 GMT:
>time=2018-02-12T23%3A20%3A50Z

is it possible that this should read : 
>time=2018-02-12T23%3A20%3A5**2**Z

**Comment by cportele** [comment]
Indeed! Thanks for spotting this.
