### ISSUE TITLE
Reusable Concepts from OASIS

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/WFS_FES#146]
SensorThing uses the [OData standard](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html) from OASIS to guide their API design.  It looks like OData has already addressed many of the issues we are exploring in WFS 3.0.  Take a look.

**Comment by akuckartz** [comment]
Looking at the design of OData makes sense, but is is not necessarily as RESTful, Linked Data and Web-oriented as I would like.
