### ISSUE TITLE
Put introduction of OpenAPI description styles in a more prominent section of the specification

### ISSUE THREAD

**Issue by aaime** [opengeospatial/WFS_FES#147]
We discussed ticket https://github.com/opengeospatial/ets-wfs30/issues/28
and found out the specification provides guidance on how to expose the OpenAPI based on "Annex B: OpenAPI definition example (Informative)".

An informative annex might be easily overlooked by someone just checking the mandatory behavior, maybe the main body of the specification could introduce the two styles directly, inviting people to read the annexes for examples?

**Comment by cportele** [comment]
This belongs into the OpenAPI conformance class (chapter 9). To make this clear, we could add a permission statement to make it explicit that both variants are consistent with the requirements.

**Comment by cmheazel** [comment]
Here are the topics I have identified so far:
1) Bootstrapping - how to access a protected API
2) How to use Security Schemes and Security Requirements (these are context sensitive)
3) How to use Server objects (these are context sensitive)
4) How to use Parameters (these are context sensitive)
5) Alternative Schemas - a useful addition which is not yet documented in the OAS spec.

**Comment by cmheazel** [comment]
How shall we address these topics?
One goal of WFS 3.0 is to provide a concise specification.  Explanatory content has been intentionally excluded.  
Yet Andrea makes a good point that a developer may overlook that information if it is not included.
One option is to flag sections of the normative spec which may be tricky to implement, and include a reference to where the developer should go for more information. 

Thoughts/consensus?

**Comment by cportele** [comment]
That was the intent of my proposal. And a permission statement is also a normative statement. For security aspects/guidance I hope that we can get ideas out of Testbed 14 what to include as (brief) guidance in the spec. We could add more explanatory content to the guide or elsewhere and link to it.

**Comment by cportele** [comment]
Discussion in 2019-04-29 call: Add a reference to Annex B in 7.3.2 (`/api` response). There is already a reference in 9.1 (the OpenAPI conformance class).
