### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/WFS_FES#148]
In section 6.2, the first bullet point says "When solids are used a geometries (e.g. in a 3D city model)"

The 'a' should probably be either "as" or "for".

**Comment by cholmes** [comment]
Note with GitHub it's a lot easier for maintainers if you just make Pull Requests for typo type stuff, as they can just click a button and merge it. If you just hit 'edit' on any document in GitHub then it will automatically make a branch for you, and then you can easily create a Pull Request from that branch.

**Comment by PeterParslow** [comment]
That was easier than the GitHub documentation & discussions I found on the web suggested! With all their talk of having to create a fork, then a branch, reconcile online & offline repositories.... Turns out it's all hidden behind the web interface.
