### ISSUE TITLE
Support an explicit "unlimited" value for `limit`

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#152]
(Moved from a discussion on Gitter)

Currently there is no general way to explicitly state that the client wants all items, i.e. something like `limit=unlimited`. If the server has a default value for limit (and most servers will have a default) then one has to set some high limit value.

**Comment by cportele** [comment]
We could use `-1` as a special value with the meaning `unlimited` (so we can keep the parameter as an integer).

Any hard limit on the number of features returned by the server (the `maximum` in the `limit` parameter) would still apply, of course.

**Comment by akuckartz** [comment]
When there is not explicit limit, why not assume that the request is for all items?!

**Comment by tomkralidis** [comment]
@akuckartz the goal here is for servers with collections of millions of features not to allow downloading an entire dataset with default parameters.

**Comment by akuckartz** [comment]
So this is about deliberately making it a little bit more difficult for clients to ask for complete data? And the proposal is to do that by making the API more complex for clients and servers without adding or removing functionalities?

If that is a correct understanding, then I disagree with the proposal. Protecting servers can and should be done differently.

**Comment by akuckartz** [comment]
See also: #165 and #23

**Comment by cportele** [comment]
13-MAY-2019 Conference call: This applies only for cases that have a default value for limit, but no maximum value. These are probably rare, so maybe this is not something for the Core? In any case, if such a special value is needed, it should be an explicit value `unlimited`.

**Comment by cportele** [comment]
20-MAY-2019 Conference call: Decided to leave this leave this outside of the core unless a case can be made that this is important for many deployments.

**Comment by cportele** [comment]
Conference call, 3 June 2019: Closing this issue as there was no further discussion. If new aspects are to be considered, the issue can be reopened.
