### ISSUE TITLE
Can we remove the mention to HTTP status codes in requirements in the WFS 3.0 core?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#158]
I believe the whole purpose of the WFS 3.0 is to use HTTP/HTTPS as a protocol (the so called ROA style) instead of inventing a protocol on top of HTTP (the previous SOA style).

I believe that that HTTP status codes should not be part of requirements in WFS 3.0. If WFS 3.0 uses pure HTTP the successful response status code is defined by HTTP and not by a requiriment in the WFS 3.0 core.In the future other status codes can emerge from the work on W3C groups and contradict a requirement in WFS 3.0. 

Requirement 2,4,6 mentions status code 200 in a normative text. This is redundant with requirement 7.

**Comment by cportele** [comment]
See also #105 where we discussed to what extend we list/describe status codes in the text. I agree that mentioning the `200` in the requirements is redundant, the idea was to be explicit, even if returning 200 is implied from the http standard. 

I do not have a strong opinion whether we should remove the `200` from the requirements or keep them.

**Comment by cportele** [comment]
Discussion in 2019-04-29 call: Yes, there is some redundancy, but it is small and helpful to readers in making the connection between the status code and the content of the response.

**Comment by cportele** [comment]
Conference call, 3 June 2019: Closing this issue as there was no further discussion. If new aspects are to be considered, the issue can be reopened.
