### ISSUE TITLE
Retrieve the Application Schema and GML SF

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#159]
Hi,
The WFS 3.0 seems to be application schema-less. This means that you do not have to deal with tedious applications schemas and define feature types to work with WFS 3.0 and GeoJSON. Features are grouped in collections but I believe that this does NOT means that all features in a collection shares the same feature type. I'm not arguing about this. This is fine. It reduces complexity and lowers the entry barrier for the non-geo people (and for many geo people too).

BUT: GML SF still requires a an application schema. My question is: how can I get the GML applications schema of a collection? GML people could miss the DescribeFeature in WFS 2.0. 

A possible answer could be: There is NO application schema in a collection and the GML schema is generated on the fly for each query to the server. Each time that a GML document is server, it has a link to a "tailored" application schema and you cannot "anticipate" it. I could be fine with this answer but the topic is confuse and "bends" the way GML was generated in the past where there was some kind of agreement between client and server on the GML application schema to use. This deserves a subsection in the document clarifying the issue.

Just a clarification: As a software developer trying to build an import library for GML, I was never able to read and use a XSD so I ended up with a reading the GML objects and modifying the structure of my internal database each time I find a new attribute. That was not a god design for GML but it was very convenient to recycle when I modified the code to read GeoJSON. What I'm trying to say is that IMHO we can live without application schemas and this is not a problem in WFS 3.0

**Comment by cmheazel** [comment]
OpenAPI provides a Response Object for each operation.  The Response Object includes a Media Type Object.  Media Type Objects include a description of the format and encoding of the response.  This attempts to address the application schema requirement, but is insufficient.  So there is a new draft capability (to be made formal in version 3.1) which allows the Media Type to reference one or more external "schema" definitions.  This external "schema" can be anything.  The particular example I supplied when lobbying for this capability was ISO 19115 metadata. I need both the XML schema and a collection of schematron files to fully define this response.

**Comment by cmheazel** [comment]
We have made it a point not to add too much explanatory information in the standard.  By capturing this information in the Users Guide, we can make it available without cluttering up the normative bits.

**Comment by cportele** [comment]
See #56 and #129. 

@joanma747 - can we close this as it seems to be a duplicate / covered by the other issues?

**Comment by cportele** [comment]
Closed as a duplicate. @joanma747 - please reopen, if anything is not covered in the other issues.
