### ISSUE TITLE
Language negotiation. Use the HTTP header for it?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#161]
Languages are important in a world that does not only speak English. If we want WFS 3.0 to be accepted by INSPIRE we need to provide a language mechanism. Actually we could use the current language negotiation mechanisms that web browsers use in the headers.

I'm only asking to include a recommendation for languages saying that accept-languge is fine:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4

**Comment by cportele** [comment]
Yes, the idea to leverage the standard web/http mechanisms, so this is how multiple languages should be supported by a server. It is not clear to me whether we need any normative text, but informative text in the Core or in the Guide might be a good idea.

**Comment by pvretano** [comment]
For the embedded link case we probably need to handle this the same way we handle content negotiation.  That is to say that we need words similar to those in the core around content negotiation indicating that for the embedded link case servers might want to have another mechanism for requesting languages (e.g. lang= or .../collections/en_CA/inwatera_1m/items or something along those lines).
