### ISSUE TITLE
Clarify server behavior when invalid bbox coordinates are used

### ISSUE THREAD

**Issue by aaime** [opengeospatial/WFS_FES#163]
The CITE tests are currently issuing requests with a bbox such as "70.0, -20.0, 70.0, 160.0", note the latitude at 160° north, expecting a non error answer in return.

Previous version of the WFS specification demanded an error to be returned in such case, as the latitute value is outside the valid range. The current specification does not say what the expected behavior should be, but the compliance tests restrict it to a tolerant approach in which no error is returned.

The specification and CITE test should be aligned, either by having the specification explicitly allowing out of range values, or the CITE tests accepting errors as a possible answer.

**Comment by cportele** [comment]
15-April-2019 Teleconference: Clarify in the spec for the bbox parameter that this is an error and the server has to return an error.
