### ISSUE TITLE
Paging testability and reaching last page

### ISSUE THREAD

**Issue by aaime** [opengeospatial/WFS_FES#166]
During today's compliance meeting another issue was raised about paging links testability, related to this ticket:
https://github.com/opengeospatial/ets-wfs30/issues/43

In particular, in order to test the paging support, one would have in theory to ask for 3 pages:
* The first page, which would only have a "next" link
* The last page, which would only have a "prev" link
* A page in the middle, which should have both

The problem is, with random paging gone, the only way to reach the last page is to follow the breadcrumbs (next links) from the first down to the last page. The CITE tests are open ended and could be run against whatever server, providing whatever collection contents. 
Some services online might be built to server  a specific dataset, and a very large one, hence be testable only with that one.

The CITE test ticket above discusses some approaches, but maybe the specification could also be modified to make this easier (thinking out loud, maybe by having a "last page" link too)

**Comment by cportele** [comment]
The problem is that we have removed requirements for offset or even the `prev` links on purpose, at least for the Core. See the (lengthy) discussion in #23. Therefore, testing can only go from first to last page and nothing else.
