### ISSUE TITLE
ATS Cleanup

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/WFS_FES#169]
It would appear that the Abstract Test Suite is not perfect (how can that be!).  The ATS_Update branch has been created to handle updates and fixes.  Please associate any updates with an issue, tagged using the new "Document: Abstract Test Suite" label.

**Comment by cportele** [comment]
Discussion in the 2019-04-29 call: Update the ATS once we have addressed all/most of the open issues, not as part of the current edits. This should be before the hackathon.

**Comment by cportele** [comment]
I am closing this issue, for tracking the ATS update we have #112.
