### ISSUE TITLE
Link to landing page from all responses?

### ISSUE THREAD

**Issue by sampov2** [opengeospatial/WFS_FES#181]
I would like to raise a topic for discussion: should responses from a WFS 3.0 should link back to the landing page of the service?

This would allow clients to backtrack from any server response to the landing page and retrieve more information about the service. This would allow clients to discover which extensions are supported by the service as well as find related documentation as well as the collections available in the service.

**Comment by akuckartz** [comment]
Which RDF property so you suggest for this?

**Comment by sampov2** [comment]
By RDF property, do you mean the rel value of the link? I think "home" might be appropriate

**Comment by pvretano** [comment]
08-APR-2019: Teleconference notes:  The core already defines a links section in most responses which gives implementors the option to add a home link and/or to interlink their service as much as they like.  The sentiment of the group was that making this mandatory was a bit too strong and a better case would be required before going that.

**Comment by cportele** [comment]
Conference call, 3 June 2019: Closing this issue as there was no further discussion. If new aspects are to be considered, the issue can be reopened.
