### ISSUE TITLE
OGC Web Services Common?

### ISSUE THREAD

**Issue by rmam-spinworks** [opengeospatial/WFS_FES#186]
As the [OGC Web Services Common](http://www.opengeospatial.org/standards/common) specification is used to specify "many of the aspects that are, or should be, common to all or multiple OWS interface Implementation Standards", and taking into account that "Remote-Procedure-Call-over-HTTP" implementations of OGC interfaces is a somewhat novel idea, are there any plans to propose a RESTful encoding of OGC Common v2.0 based on WFS 3.0?

**Comment by pvretano** [comment]
Yes there is ... work is underway now to define what will be in OWS Common v2.0 but I imagine that it will be things like definitions of the landing page, /api resource, /conformance resource how spatial and temporal predicates should be encoded, etc.  As I said, being discussed now ...

**Comment by rmam-spinworks** [comment]
That's good to hear.  I'm assuming you're referring to OWS Common v3.0, as v2.0 was released way back in 2010.

Is there any chance to follow those discussions?  I'm interested in the subject and I'd like to be aware of where things are heading.

**Comment by ogcscotts** [comment]
We do have an active OWS Common Standards Working Group and there is also the stub of a standard here: https://github.com/opengeospatial/oapi_common

The discussion of the modernization of common elements is continuous at our TC Meetings!

**Comment by pvretano** [comment]
Doh! ;) Yes, I suppose it would be a 3.0 ... Thanks @ogcscotts was just about to send that information!

**Comment by rmam-spinworks** [comment]
That's good to hear.  Thanks for the info and keep up the good work!

**Comment by cportele** [comment]
@rmam-spinworks - See #190, this should address your point. Can we close this issue?

**Comment by rmam-spinworks** [comment]
@cportele it does.  Very interesting and helpful read. Thank you for pointing it out.
