### ISSUE TITLE
New Title

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#189]
WFS has been the first group within OGC to work on a revision of an OGC Web Services standard as a Web API with OpenAPI support. By now, several other groups in OGC are working on similar revisions, too.

The Closing Plenary of the February 2019 OGC TC Meeting has discussed the naming of these revisions. The current proposal is to change the names and move towards the following pattern: "OGC API - {ResourceType}". 

That is, "Web Feature Service" would become "OGC API - Features". There was no formal motion yet, but there were no concerns raised by members during the discussion, only supportive comments. 

For now, I have created this issue so that we can keep track of the title discussion and to collect comments.

**Comment by akuckartz** [comment]
"Web Feature Service" is better than "OGC API - Feature":
* Well known established name
* Web Service is more specific and more precise than API
* No need for organisation name in specification name (compare with names of W3C Recommendations)

**Comment by ayiemba** [comment]
I feel "OGC {ResourceType} API" makes more sense. However, I wouldn't have an issue with whatever name it's called as long as there is support for OpenAPI.

**Comment by timoruohomaki** [comment]
Was there any discussion on short forms or acronyms? Will "OGC API - Features" still also be a "WFS"?

**Comment by jvanulde** [comment]
I'm with @akuckartz regarding the organization name. How about "Geo API" for features, "Map API" for maps and "Catalogue API" for catalogue etc.? Note that the concept of "features" is not widely understood, hence the "spatial things" proposal. I suppose we could prefix with "Open" (e.g. Open Geo API) if warranted (e.g. collision with &copy;, &reg;, &trade;).

**Comment by ogcscotts** [comment]
We have three goals in the naming: (1) to form a consistent pattern that matches the style of W*S, (2) allow W*S to exist concurrently as those standards are not likely to disappear from implementations any time soon, and  (3) ensure that the standard names indicate the geospatial context. We also have to watch for confusion with OS Geo and the Opengeo Suite.

**Comment by lieberjosh** [comment]
OGC API for Features would become OAF. A bad implementation would be a clumsy OAF. 

Perhaps "OGC Feature API" would be better, OFA for short, giving OMA, OCA, and OPA ( a greek form of processing). 

Catalog is still iffy. Perhaps "OGC Registry API" -> ORA. Add Common Query Language and you have ORACQL.

—Josh

**Comment by ogcscotts** [comment]
clever!

**Comment by pvretano** [comment]
@lieberjosh As the only Greek currently engaged in this discussion, I fully support OPA! ;)

**Comment by lvdbrink** [comment]
Like @jvanulde I would prefer to avoid the term "Feature" as it can (and does) cause confusion when engaging with a wider audience, as discussed in the [Spatial Data on the Web Best Practices]( https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry). 

Maybe Spatial data API?

**Comment by nmtoken** [comment]
Just as an aside, and probably spotted before, but...

Spatial Data on the Web Best Practices <https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry>

EXAMPLE 2: Eddystone Lighthouse geometry (encoded as GeoJSON [RFC7946])
{
  “geometry”: {
    “type”: “Point”,
    “coordinates”: [50.184, -4.268]
  }
}

That's wrong, GeoJSON is long lat so coordinates should be -4.268, 50.184 (just off the south coast of the UK)

James

-----Original Message-----

**Comment by ogcscotts** [comment]
@lvdbrink @jvanulde We still do need to acknowledge that "feature" means something very specific in a geospatial context that is important. "Spatial Data" is too generic and something like "Vector" would cause even more confusion. Perhaps "Spatial Feature?"

**Comment by cportele** [comment]
I would say that we either use "feature" (because this reflects current practice) or something different like "spatial thing" (and explain the relationship to the term "feature").

**Comment by lvdbrink** [comment]
@nmtoken would you mind creating an issue in https://github.com/w3c/sdw? Probably spotted before, but not reported to us yet... 

@ogcscotts I guess it's a matter of who to confuse and who not to confuse... To people not from the geospatial domain (like me, originally) the term feature means something like 'characteristic' and most often, in an IT context, 'something a system can do' (a functional feature).  

'spatial thing' like we chose in SDWBP is an option...

**Comment by royrathbun** [comment]
What if you put 'Spatial' in FRONT of API, thus characterizing the subjugates as relating to what APIs OGC has perview over.  Unless this was poo-pooed earlier, then unregard....I've been distracted lately...

**Comment by prushforth** [comment]
Note that [GeoJSON](https://tools.ietf.org/html/rfc7946#section-1), perhaps the market leader in popular geography encodings for the Web, uses "Feature" and "FeatureCollection".  [MapML](https://maps4html.github.io/MapML/spec/#the-feature-element) has the `<feature>` element because of this. So my view is that "feature" is well enough accepted nowadays.

**Comment by pvgenuchten** [comment]
In the end it's just a standard-name, but in the list below Feature is the least informative... However we're all used to the term feature, having to identify by it's standard-name that we're exposing schema.org/Things (often having one of its properties being spatial) will be hard 

OGC API - Feature
OGC API - Catalogue
OGC API - SensorObservation
OGC API - Coverage
OGC API - Process

**Comment by pvretano** [comment]
08-APR-2019 Teleconference: Peter to hold informal SWG vote on the name that was agreed on in the teleconference (i.e. OGC API - Features).

**Comment by cportele** [comment]
The decision is to use "OGC API - Features - Part 1: Core" as the title. The "OGC API - {resourceType}" part is fixed and it was decided to use "features" as the name of the resource type (and add an explanation about the term right at the beginning). The use of "Part {n}: {title}" and the use of a dash is consistent with the existing practice in ISO.

There is PR #208 to implement the change. 

In paragraphs I have dropped the dashes as those dashes conflict with the normal interpretation of dashes in sentences. 

As this is a general OGC API topic, see also https://github.com/opengeospatial/oapi_common/issues/22.
