### ISSUE TITLE
uri strategy and supporting various wfs versions

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/WFS_FES#191]
While reading #190 and #64 i imagined there may be another level of complexity which may not have been considered yet (maybe i missed it in the discussion), which is a need to support multiple versions of WFS over time. I expect after a while version 3.1 or 4 of wfs will be considered (aka ogc-api:feature-v2), or is it considered these will be backwards compatible? 

I guess there should be a distinction between uri's (which should be persistent, so not include a version number) and actual operations to retrieve the things behind those uris. A forward rule could guide the user from the uri to the operation fetching the thing. This however triggers the following questions: 
- to what version of the WFS should that user be guided (most recent available?)
- should there be an optional version parameter/header?
- how does the client know which versions of WFS are supported by that server

Looking forward to hear your thoughts (or links to existing threads)

**Comment by cportele** [comment]
Versions 3.x (or 1.x) will not break any requirement in 3.0/1.0. And currently there is no plan for another major version.

That said, a publisher may also mint other canonical URIs for features / spatial things separate from the URI and redirect to the API URIs depending on the strategy of the organisation, but the idea is that this (and the additional redirects) should not be necessary.

> to what version of the WFS should that user be guided (most recent available?)

Yes, the most recent available.

> should there be an optional version parameter/header?

No. The OGC API specs do not specify complete APIs as such (these will be defined by a data publisher and will typically include other resources, too, and will often include a version in the path), but API elements / building blocks. Therefore, no version information in the path (or header).

> how does the client know which versions of WFS are supported by that server

Look at `/conformance`, the conformance classes listed there include the version of the spec.

**Comment by cportele** [comment]
I am closing this issue as the question has been addressed and there is no further discussion.
