### ISSUE TITLE
Result Set consistency during paging

### ISSUE THREAD

**Issue by aquaglia** [opengeospatial/WFS_FES#192]
I do not see any mention of result set consistency during paging.
If a query returns many objects, how can I be sure that none is modified during the time I paginate through the results?

Is this something that falls under this disclaimer ("transactions")?
_Additional capabilities such as support for transactions, complex data structures, rich queries,
other coordinate reference systems, subscription/notification, returning aggregated results, etc.,
may be specified in future parts of WFS or as vendor-specific extensions._

**Comment by pvretano** [comment]
08-APR-2019: Teleconference note.  We will add a sentence to the core indicating that, like WFS 2.X, paging is not safe.  In WFS 2.X there was a mechanism for a server to declare that paging was safe but we don't think that is necessary in the Core.

**Comment by rcoup** [comment]
@aquaglia as discussed in #23, the normal way is for the server to maintain search/query/cursor/db state and pass next-page links with URLs encoding that state. This is obviously all very backend-dependent.

Simplistic `?offset=30&count=10` paging approaches won't be consistent.
