### ISSUE TITLE
suggestion not to use a property called type (on link)

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/WFS_FES#197]
In case we foresee a json-ld representation of the collections document and considering discussion [here](https://github.com/geojson/geojson-ld/issues/39), i would opt for certainty and not use a property called "type" (now used on "[link](https://github.com/opengeospatial/WFS_FES/blob/1762e8890f9bde50ce3c9e79bbcb6953d139214d/core/openapi/schemas/link.yaml#L11)"). Or any reserved keyword on json-ld.

link.format or link.encoding could be an alternative?

**Comment by cportele** [comment]
06-MAY-2019 Conference call: Chuck will investigate, if it really is a problem to use "type" inside of the link object.

**Comment by cmheazel** [comment]
- "@type" is a json-ld reserved keyword.
- The context section of a json-ld document maps terms to IRIs.
- json-ld prohibits the use of a reserved keyword as a term in the context section.
- From [here](https://github.com/geojson/geojson-ld/issues/39) it appears that some json-ld parsers cannot distinguish between "type" and "@type".
- RFC 5988 uses "type" as a parameter for Web Linking.  This is functionally the same as the type parameter in [link](https://github.com/opengeospatial/WFS_FES/blob/1762e8890f9bde50ce3c9e79bbcb6953d139214d/core/openapi/schemas/link.yaml#L11)  
- So our use of the type parameter should be legal.
- However, in RFC 5899 the type parameter resides in a parameter section following the IRI.  It is very unlikely that it would be interpreted as anything other than a parameter. That is not the case in json and json-ld.

Conclusion: While our use of "type" in [link](https://github.com/opengeospatial/WFS_FES/blob/1762e8890f9bde50ce3c9e79bbcb6953d139214d/core/openapi/schemas/link.yaml#L11) is proper and legal, a casually implemented parser may still confuse "type" in an Object with "@type" in the Context. Is this an acceptable risk?

**Comment by cportele** [comment]
But even if we would change "type" to something else in the link object (eg, "mediaType"), "type" is still used in GeoJSON objects. 

Does anyone know, if the JSON-LD 1.1 revision is considering changes to avoid breaking existing JSON encodings?

**Comment by cmheazel** [comment]
@cportele Take a look at the discussion linked to on the fourth bullet.  GeoJSON is broken. 
"ordinary GeoJSON can not be converted to JSON-LD merely by attaching one of this project's context docs. You'd actually need to edit the GeoJSON doc itself."  
Now I understand that there are other good reasons why you would not just stick a context on GeoJSON and call it GeoJSON-LD.  I also acknowledge that this is not an insurmountable problem. Is it a problem we are prepared to take on?

**Comment by cportele** [comment]
My conclusion would rather be that JSON-LD 1.0 is broken, not GeoJSON.

But my point is that even, if we change "type" in the link object we still could not use JSON-LD 1.0 with the GeoJSON conformance class. So if we add a JSON-LD conformance class in the future, we could also address this then.

Note that JSON-LD 1.1 is looking at compatibility with GeoJSON, see https://www.w3.org/TR/json-ld11/#example-71-coordinates-expressed-in-json-ld.

**Comment by cmheazel** [comment]
Resolution: We understand the issue and are prepared to deal with it when and if it impacts the OGC API-Features standard.

**Comment by cportele** [comment]
Discussion 17 June: No more comments about the resolution, so we close it.
