### ISSUE TITLE
Problem with the feature catalogue example

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/WFS_FES#198]
Recommendation 7 states the following:

![image](https://user-images.githubusercontent.com/11427611/56039039-aa192280-5d33-11e9-8efb-1e457759f897.png)

So, an example of a resource that describes the dataset (and therefore, as a consequence, also the dataset distribution) is a feature catalogue.

However, in the example provided later on, a feature catalogue is given as an example of a resource that describes a feature collection, not a dataset:

![image](https://user-images.githubusercontent.com/11427611/56040468-c36f9e00-5d36-11e9-89a1-08202e758826.png)

**Comment by cportele** [comment]
I think the example is consistent with the text. The recommendation states:

* If a resource describes the dataset, the link should be in the `links` object on the top-level.
* If a resource describes a collection in the dataset (in this case the buildings), the link should be in the `links` object of the collection.

In the example, the feature catalogue is just about buildings and thus in the links object of the building collection  object while the XSD is for the whole dataset and therefore in the links object at the top.

**Comment by heidivanparys** [comment]
> In the example, the feature catalogue is just about buildings and thus in the links object of the building collection object while the XSD is for the whole dataset and therefore in the links object at the top.

The example may be too simple in order to be able to illustrate the difference between a dataset, distribution and a feature collection? As both the dataset (distribution) and the feature collection are about buildings:

> This document uses a simple example throughout the document: The dataset contains buildings and the server provides access to them through a single feature collection ("buildings") 

I think the main reason for my confusion is that normal practice where I work is to consider a feature catalogue as a description of a data set, and not to relate a feature catalogue to only to one of the distributions of the dataset (GML, SHP, WFS, ...) or to a subset of the features in a dataset.

![Resources associated with dataset and distribution](https://user-images.githubusercontent.com/11427611/56052240-31c15a00-5d51-11e9-8b9c-8a2a71a51035.jpg)

Of course the WFS standard should not dictate how to organize data, metadata and related resources. On the other hand, if many others use the same way of doing this, it may confuse other people than me too.

**Comment by cportele** [comment]
OK, it is clearly not the idea to confuse, so probably the easiest is to simplify the example by removing the feature catalogue. It is an example after all and the feature catalogue itself is irrelevant, at least for the specification. 

The topic of which descriptive metadata should be associated with which resource (in order to be useful to users / developers) is still a relevant topic, but not something for the Core.
