### ISSUE TITLE
The concept of "feature collections metadata" and "feature collections"

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/WFS_FES#199]
It seems that all places where "feature collections metadata" is written, a perhaps better and more straightforward term would have been "dataset distribution metadata" (or the shorter "distribution metadata"). And quite some occurrences of "feature collections" could probably be replaced with "distribution".

This seems to be confirmed by the following paragraph:
![image](https://user-images.githubusercontent.com/11427611/56048660-3e8d8000-5d48-11e9-8663-025bd778844b.png)

Examples of the occurence of "feature collections metadata":

![image](https://user-images.githubusercontent.com/11427611/56048401-bd35ed80-5d47-11e9-9b8d-8c7fdb41288a.png)

![image](https://user-images.githubusercontent.com/11427611/56048742-6a106a80-5d48-11e9-8ba9-964e918cc787.png)

As a consequence, the identifiers of the requirements related to distributions should maybe be reconsidered too: /req/core/**fc**-md-op.

**Comment by pvgenuchten** [comment]
I guess the use of "feature collections metadata" is related to the fact that the /collections operation returns both metadata as well as the distribution, compare it to the getcapabilities request in wfs2. Per collection there is metadata like name, title, crs, extent. See https://github.com/opengeospatial/WFS_FES/blob/master/core/openapi/schemas/collectionInfo.yaml.

**Comment by cportele** [comment]
15-April-2019 Teleconference: Agreed that we need to have consistent naming. Dataset distribution reflects the underlying model and the relationship to the dataset, feature collections metadata reflects more the content that you get back. To be consistent we will use "feature collections metadata" but explain the relationship with dataset / dataset distribution.

> It would be good to discuss if there is a need/possibility to add more dataset-metadata as part of the collectioninfo, such as keywords, metadata link, temporal coverage.

For the Core we have an appropriate amount of metadata. However, implementations (or extensions) may add additional information (very simple in JSON/HTML, a bit more complicated in XML right now).

**Comment by cportele** [comment]
resolved by #208
