### ISSUE TITLE
Query parameter collisions

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/WFS_FES#20]
How should a server handle the case where the property name of a feature collides with the name of one of the defined api parametrs?  COUNT, RESULTTYPE, BBOX are all api parameter names that could conceivably also be property names in a feature.
Perhaps we might consider prepending the API parameter names with "wfs:".  Just a thought.

**Comment by cportele** [comment]
Yes, that is something we will have to address in some way. The same is also true for a feature collection that someone wants to call "api" (maybe not very likely, but we have to clarify this).

**Comment by cportele** [comment]
Agreement on 2018-02-01: Not critical for now, keep it open and wait for feedback from implementations.

**Comment by cportele** [comment]
#64 would resolve the naming collisions for path components (not for query parameters)

**Comment by sampov2** [comment]
Another danger with this collision is in cases where a client assumes (wrongly) that a server supports a particular query parameter. This might happen in cases where a client uses non-core functionality that is widely deployed but just not present in a particular server. In those cases the server ends up parsing this query parameter as a property filter and in most cases no feature will have such property with the given value and the server gives empty results to clients. This is counter to how web services usually just disregard any unknown parameters.

**Comment by cportele** [comment]
@sampov2 - Property filter parameters are explicitly declared by the server. That is, I don't see that as a real issue. First, clients that assume certain conformance classes should check `/conformance`. But even if they don't and use something like `resultType=hits` in the request without checking, a server that does not support such an extension would ignore this parameter unless it has declared that `resultType` is a feature property that can be filtered (which is very unlikely).

**Comment by sampov2** [comment]
Good point that parameters are declared in the API. This should alleviate the problem I was thinking about.

As a side note however, I do not expect to see most clients looking at /conformance at all. As one of the drivers behind this new kind of API is to attract developers and users outside the OGC/GIS community, we need to ensure these APIs are easy to use and cannot require parsing conformance classes etc. to get value out of the APIs and data. Tthis is just a comment, not critique. I think we're on the right path)

**Comment by cportele** [comment]
I am closing this as the issue has been addressed.

(On the side discussion of /conformance: Yes, clients that do not know or care about OGC and their standard will not look at the conformance declaration and using the API does not depend on accessing /conformance first. This is for "generic" clients that are aware of the OGC API standards.)
