### ISSUE TITLE
Recommendation regarding license in the core

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/WFS_FES#202]
I would like to suggest to add a recommendation regarding license information in the WFS core.

I am well aware of the fact that license information usually will be present in an associated DCAT or ISO 19115 metadata record, however, I would like to argue, based on the following statements and references, that information regarding the license is important enough to be given its own place in the core:

> The presence of license information is essential for data consumers to assess the usability of data. User agents may use the presence/absence of license information as a trigger for inclusion or exclusion of data presented to a potential consumer. [Best practice 4 in [Data on the Web Best Practices](https://www.w3.org/TR/dwbp/)]

> Explicit licensing is essential to provide clarity and certainty to users and reusers (and is needed even if you want your data to be ‘public domain’). [[Making Your Data Open: A Guide](https://opendatacommons.org/guide/)]

> It is best to embed information about the licence that some content or data is available under directly within the content or data. This ensures that the licensing information is carried around with the content or data. [[Publisher’s Guide to Open Data Licensing](https://theodi.org/article/publishers-guide-to-open-data-licensing/)]

> Licenses should be published and linked to open data to ensure data users can easily find and understand the conditions of data access and reuse. [[Principles - International Open Data Charter](https://opendatacharter.net/principles/)]
![image](https://user-images.githubusercontent.com/11427611/56566468-05100c80-65b3-11e9-8d6b-a262f3a14934.png)

I noticed that the [IANA Link Relation Types](https://www.iana.org/assignments/link-relations/link-relations.xml) overview contains a "license" relation name, described as "Refers to a license associated with this context."

An updated buildings example could thus look like follows:

```json
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/foobar.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "XML schema for Acme Corporation data" }
  ],
  "collections": [
    {
      "id": "buildings",
      "title": "Buildings",
      "description": "Buildings in the city of Bonn.",
      "extent": {
        "spatial": [ 7.01, 50.63, 7.22, 50.78 ],
        "temporal": [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ]
      },
      "links": [
        { "href": "http://data.example.org/collections/buildings/items",
          "rel": "items", "type": "application/geo+json",
          "title": "Buildings" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
          "rel": "license", "type": "text/html",
          "title": "CC0 1.0" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
          "rel": "license", "type": "application/rdf+xml",
          "title": "CC0 1.0" }
      ]
    }
  ]
}
```

**Comment by cholmes** [comment]
+1 - we put license as a required field in [STAC collections](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md) 

We're not set on the exact semantics, but similarly felt that license should really be included.

**Comment by cportele** [comment]
Discussion in 2019-04-29 call: Agreement to add it in 7.11.2. Licenses are part of a bigger concern that involves security/access control, but it does not hurt to add this as a recommendation, in particular for open data licenses.

**Comment by m-mohr** [comment]
> +1 - we put license as a required field in [STAC collections](https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md)
> 
> We're not set on the exact semantics, but similarly felt that license should really be included.

This is actually fully compatible with STAC. We have a license field in the Collections which follows [SPDX](https://spdx.org/licenses/) expressions or can be set to `proprietary` and then allows to include a license link exactly as it is proposed here. So except the missing license field, the actual link is fully compatible.
