### ISSUE TITLE
MEDIA type for GeoJSON is not correct

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/WFS_FES#203]
[The GeoJSON media type](https://sgillies.net/2014/05/22/the-geojson-media-type.html#) is **application/vnd.geo+json**  

but https://github.com/opengeospatial/WFS_FES/blob/master/guide/section_12_mediaTypes.adoc has 

> JSON media types that would typically be used in a WFS that supports JSON are

> application/json  for feature collection metadata, and

> application/geo+json  for feature collections and features.

but should be: 

application/vnd.geo+json for feature collections and features.

and the buildings example should be:

    "links": [
        { "href": "http://data.example.org/collections/buildings/items",
          "rel": "items", "type": "application/vnd.geo+json",
          "title": "Buildings" },
        { "href": "http://example.org/concepts/building.html",
          "rel": "describedBy", "type": "text/html",
          "title": "Feature catalogue for buildings" }
      ]

**Comment by cportele** [comment]
The media type in the vendor branch is outdated as a result of the standardization of GeoJSON in IETF. The media type used in the draft is correct.

See https://www.iana.org/assignments/media-types/application/geo+json or https://tools.ietf.org/html/rfc7946#section-12.
