### ISSUE TITLE
Minor editorial issues

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/WFS_FES#204]
- [x] clause 7.1: "The CollectionResponse may include metadata about the number of selected and returned features" should be replaced by "The CollectionResponse may include the number of selected and returned features" ("metadata about" is redundant).
- [x] recommendation 8: "if [...], you SHOULD support a parameter with [...]" should be replaced by "a parameter with [...]" SHOULD be supported" (see https://github.com/opengeospatial/templates/blob/master/editor_guidance.adoc#person)
- [x] Replace "Metdata about the feature collections shared by this API" by "Metadata about the feature collections shared by this API" in openapi.yaml and openapi-buildings.yaml

**Comment by cportele** [comment]
This will be fixed by PR #208. Thanks @heidivanparys!
