### ISSUE TITLE
UML model: XMI

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/WFS_FES#209]
Is it possible that WFS_FES/core/UML/ISO 191xx-1 Edition 1.xmi is not in line with the figure in the standard, WFS_FES/core/standard/figures/PT1_FIG01.png ? Or is the XMI file to be found somewhere else?

I would like to comment on the figure, but it would be easier if I had the XMI file behind it, in order to show suggestions for improvement.

**Comment by cportele** [comment]
For the master branch the XMI and PNG should have been consistent, but not yet for the `issue-189` branch. I have updated the XMI file at https://github.com/opengeospatial/WFS_FES/tree/issue-189/core/UML.

**Comment by cportele** [comment]
resolved by #208
