### ISSUE TITLE
Add anchors for each requirement/example/etc.

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#225]
This will support deep links to specific parts of the document, not just the sections.

**Comment by cmheazel** [comment]
In API Common I separated requirements from recommendations.  I also made some formatting changes in an attempt to improve readabilty.  Take a look at these and let me know if you want the same in API-Features.

**Comment by cmheazel** [comment]
@cportele Can you provide an example of what you have in mind?

**Comment by cportele** [comment]
> I also made some formatting changes in an attempt to improve readabilty. Take a look at these and let me know if you want the same in API-Features.

The change is that you combined multiple requirements into one and created "sub-names" like A, B, etc.? I have concerns about this approach. Separate requirements should remain separate requirements, each with their own URI.

> @cportele Can you provide an example of what you have in mind?

I want to be able to have links to each relevant element in the HTML version of the document. Currently I can only reference sections (eg http://docs.opengeospatial.org/DRAFTS/17-069r1.html#string_i18n references 7.10) or select document elements (eg http://docs.opengeospatial.org/DRAFTS/17-069r1.html#tldnr references table 1). I want to extend this so that one can create references to each table, example, requirement, recommendation or permission. And maybe more elements. I.e., there will be an anchor ("[[anchor]]") before every of these elements in the adoc source.

**Comment by cmheazel** [comment]
@cportele No, I have not combined requirements.  I have taken the existing multi-part requirements and broken out the individual parts. If you look at older versions you will find the same content, but all run together into a single body of text. 
Permissions, recommendations, and requirements now have anchors.
