### ISSUE TITLE
Add API title to landing page

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#227]
From gitter discussion:

@bradh: If I want the title for the service (i.e. above collection level), I have to get it from the openapi description? That'd be a handy thing to provide in the main / level doc.

**Comment by cportele** [comment]
Yes, that would support the use of the API by a client that knows the standard and follows a more hypermedia-driven approach (and which does not analyse the API definition). It introduces some redundancy with the API definition, but if we limit it to the title (and maybe the description) that would be ok with me.

**Comment by bradh** [comment]
The specific case: client code wants to have a user-friendly display name to go with the URL:

![image](https://user-images.githubusercontent.com/174642/59029693-51cd4f80-88a2-11e9-93b8-e7ffed1ccf33.png)

If I could avoid parsing the openapi (`rel='service'`), that would have me a server round trip just to get a reasonable display name.

**Comment by cportele** [comment]
Conference call 10 June 2019: Agreement to include the title and description in the landing page. The values should be consistent with the API definition. We do not want to go beyond title/description otherwise consistency will become more difficult. @cportele to implement this directly so that we have a clean version before the hackathon. The change is not considered controversial.
