### ISSUE TITLE
Move examples in Annex B/C outside of the document

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#239]
The examples just take up a lot of pages (if you print the document or use the pdf). It would be better to move them outside, for example to an example section in the GitHub repository.

This will also help to manage the informative examples separate from the spec.

Related to #132

**Comment by pvretano** [comment]
@cportele Yeah, good idea.  The main document should be as concise as possible.  Linking out should be a good compromise between those who want to make the document concise and those who want lots of examples.

**Comment by cportele** [comment]
Decision to move the examples in the annexes to some web-presence.

Include a persistent URI in a opengeospatial.org domain that redirects to the location of the examples.
