### ISSUE TITLE
Prepare submission package

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#243]
- [x] OpenAPI fragments (parameters, schemas, etc.)
- [x] XML schemas
- [x] update submission date on the front page, release 1.0.0-draft.2

**Comment by dr-shorthair** [comment]
Can you provide a link to preview the document?

**Comment by cportele** [comment]
@dr-shorthair - The editor's draft is here: http://docs.opengeospatial.org/DRAFTS/17-069r2.html

There is also more context in the README of the repo.
