### ISSUE TITLE
Why collections/{collectionId} exists if collections returns the same info?

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#248]
I'm probably missing something here but I'm not able to find it.

To formulate a /collections/{collectionId} I need to know the {collectionId} values.

Requirement 17B  says:
> The parameter collectionId is each id property in the feature collections response (JSONPath: $.collections[*].id).

So I need to formulate a /collections request to know the collectionId values .  Requirement 12B says that:
> The content of that response SHALL be based upon the OpenAPI 3.0 schema collections.yaml

Collections.yaml includes Collection.yaml that describes the collection. Collection.yaml is also the response of /collections/{collectionId}

So why /collections/{collectionId} exists in the first place if /collections will give me all the info in /collections/{collectionId} and I have to formulate it first anyway?

You could say that {collectionId} could be enumerated in a enum in the OpenAPI document but this is NOT what Requirement 17B says.
You could argue that actually requirements for /collections/{collectionId} (17 and 18) never say that the response should follow Collection.yaml. True. But then, what should it contain?.

**Comment by joanma747** [comment]
BTW, Actually I discover this by trying to design an "OGC API maps and tiles". 
I accidentally defined:
\collections responding only the "OGC API common part" (identical to WFS 3.0 of collection.yaml). 
\collections\{collectionId} responding an extended version of the "common part" that included also the OGC API Tiles needed elements (e.g. tileMatrixSetLink).

This seems consistent with how OGC API Features is designed and makes the information in \collections\{collectionId} response more comprehensive than the one in \collections.

I hope this is the correct decision (even if it was not what happen in the old WMTS GetCapabilities that had the full description of the tiles in the "main" capabilities document).

**Comment by cportele** [comment]
Yes, collection.yaml is "just" the core of the information about a collection. In particular, if an API supports more information it will include additional information in the /collection/{collectionId} resource. For example, information about tiles, tiling schemas, applicable styles, maps, etc. An implementation may decide to include this info also for each collection in /collections, but I expect that most implementations will eventually not do this, if the API supports more and more capabilities per collection (and more information is included per collection).

See requirement [/req/core/sfc-md-success, part B](http://docs.opengeospatial.org/DRAFTS/17-069r3.html#req_core_sfc-md-success) which requires the id/title/description/extent from collection.yaml are identical in both resources ($.collections[*] in /collection and /collections/{collectionId}) for consistency, but implies that /collections/{collectionId} will often contain more information. I.e., the approach described in the second comment is consistent with the intended approach.

**Comment by cmheazel** [comment]
@joanma747 /collections returns an array of collection metadata, one entry for each collection.  /collections/{collectionId} returns the collection metadata for a single identified collection.  One would expect that the collection metadata at the /collections level would be a summary of the metadata returned at the /collections/{collectionId} level.

**Comment by cportele** [comment]
SWG call 2019-08-12:  The question has been answered.
