### ISSUE TITLE
API features prevents support to collections of other type in a single service.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/WFS_FES#249]
Requirement 19A says:

> For every feature collection identified in the feature collections response (path /collections), the server SHALL support the HTTP GET operation at the path /collections/{collectionId}/items.

This prevents to have a collections that are features and collections that are coverages in the same service. ...or prevent that some collections are not downloadable and can only be obtained as maps.  This use case was expressed by some people in the last OGC API hachathon.

Please replace it by 
"For every feature collection that presents a link with "items" type in the feature collections response (path /collections/{collectionId}), the server SHALL support the HTTP GET operation at the path /collections/{collectionId}/items."

**Comment by pvretano** [comment]
@joanma747 I am not sure I see how this requirement prevents features, coverages or maps from being served from the same service.  The collection metadata at /collections includes an "itemType" so you know that a particular collection is a collection of features (i.e. itemType=feature).  If this is the case then the requirements of this specification apply.  If itemType is not "feature" then other requirements, outside the scope of this standard, would apply.

**Comment by joanma747** [comment]
It really depends on how you defined a "_feature_ collection". When I'm reading "feature collection" in WFS I'm never sure if it means "well, for the moment I say _feature collection_ but when we move to common it will say _collection_. 
If in this case we interpret "_feature_ collection" as "collections with itemType=feature" then this issue does not exist.
Unfortunately, I'm not sure that the "itemType" was a good idea in the first place. Please read this: https://github.com/opengeospatial/ogc_api_coverages/issues/25 were we are discussing aobut a collection that can be exposed as items and as coverages.

**Comment by pvretano** [comment]
@joanma747 This is the "OGC API - Features" specification so I hope it is clear that we are only concerned about collections of features.

**Comment by joanma747** [comment]
I believe I'm thinking in too many directions that make me interpret the requirements not by what they say. Sorry for that.

**Comment by pvretano** [comment]
@joanma747 no need to apologize for considering things at a higher level.  It is very important that this OGC API approach hangs together consistently across all OGC resource types and I appreciate that you and others are considering things at this level.

**Comment by dblodgett-usgs** [comment]
@pvretano -- this is a frustrating, if thought provoking, response. While it _is_ a feature API, a feature is really a functional view of a data resource that can just as easily be treated functionally as a coverage. OGC-API is going to need a clean way to treat a given data resource as a feature collection, a coverage, a map, or maybe a process?

So maybe "collections" should _always_ be read as _feature collections_ and we should consider some kind of structured list of "layers" that could each have a feature collection, a coverage, a process, etc.?

e.g. 
```https://acme.com/collections/``` for all _feature collections_
```https://acme.com/coverages/``` for all _coverages_
```https://acme.com/processes/``` for all _processes_
```http://acme.com/layers/``` for all "data resources" that might each have feature collections, coverages, and/or processes?

**Comment by cportele** [comment]
> While it is a feature API, a feature is really a functional view of a data resource that can just as easily be treated functionally as a coverage

@dblodgett-usgs, I think you really mean "While it is a feature API, a feature **collection** is really a functional view of a data resource that can just as easily be treated functionally as a coverage." Correct?

I would also say that this is correct for some feature collections (and maybe many of them in some communities), but for most feature collections that I have seen noone was interested in a coverage view of that data. 

So, we should find a way to support such a case without making it more complicated for the many that do not need such a view. 

My proposal would be to change itemType so that it is either a single string (as it is right now) or that it is an array of strings. Then it could be `"itemType": ["feature", "coverage"]` and Features specifies the requirements implied by "feature" and Coverages specifies the requirements implied by "coverage". I.e., we could support both views (and even more, if needed) without making the Features or Coverages specs more complicated.

Would that work?

**Comment by dblodgett-usgs** [comment]
Yes -- that is a more precise statement of what I'm getting at. There is a lot of nuance here that will probably take some testing. 

I am in complete agreement that _most_ feature collections would not be thought of as a valid coverage so this will be a rare case.

I'm not entirely clear on the implications of `itemType`. Will need to review the spec and ponder a bit. Would that be described in the hypermedia returned at the `https://acme.com/collections/` endpoint?

**Comment by cportele** [comment]
> Would that be described in the hypermedia returned at the https://acme.com/collections/ endpoint?

Yes, and https://acme.com/collections/{collectionId}. If no value is provided, it is "feature", which is the default. This is for backwards compatibility with existing implementations. 

The exact implications will only be clearer once we have additional item types specified. For "features" in Core it basically just says that if you follow the `rel='items'` link you will access the features and that the "extent" member describes the spatial/temporal extent of the features in the collection. Other specs will have to specify their implications, if they support other types of collections or views an a collection.

**Comment by dblodgett-usgs** [comment]
That seams reasonable. @joanma747 -- are you good with this concept? Maybe we should reflect this back over in https://github.com/opengeospatial/ogc_api_coverages/issues/25 ?

**Comment by pvretano** [comment]
@cportele, @dblodgett-usgs  I am not sure I like this proposal of allowing the itemType to be an array.  It seems unnecessarily complicated and requires that a client needs to understand what the array means (i.e. that there are two different views of the data).  I would prefer that two different views of the same data are materialized through the API as two different resources (e.g. feature or coverage) and then hypermedia controls are used to associate the two views (e.g. rel=related or something like that).

**Comment by cportele** [comment]
@pvretano - Yes, we shouldn't make it complicated for clients, but I am not sure that an array makes it complicated. 

On the other, after a bit more thoughts I now have doubts about such a change, too, as we would be changing the meaning of the itemType member. Until now it is about the nature of the resources in the /collection/{collectionId}/items path, and these are and will be features. That there is an additional coverage view does not change that the items in the collection are of type "feature". 

For me /collection/{collectionId}/coverage seems more like /collection/{collectionId}/map where derived resources are processed from the features in the collection.

**Comment by dblodgett-usgs** [comment]
Now we are to where we left off with @joanma747's latest comment here: https://github.com/opengeospatial/ogc_api_coverages/issues/25#issuecomment-514095398 I think? I am happy with this sort of solution. We would need some sort of mechanism to select the actual coverage (variable/attribute) you want from the coverage view of the collection, but that could be `/collection/{collectionId}/coverage/{coverageID}` or `/collection/{collectionId}/coverage?RANGESUBSET=var1,var2` ?

**Comment by cportele** [comment]
@dblodgett-usgs In my understanding the coverage view means that there is a single coverage and `/collection/{collectionId}/coverage` would be that coverage resource. The details of sub-resources, query parameters and so on to select subsets/variables/etc. should be consistent with whatever OGC API Coverages will specify for coverage resources. Does that make sense?

**Comment by KathiSchleidt** [comment]
@cportele your assumption of a single coverage per collection seems in contradiction with statements on OGC API Coverage Readme:

- http://acme.com/oapi/collections/{collectionid}/coverages -- returns a list of all coverage identifiers included in a specific collection
- http://acme.com/oapi/collections/{collectionid}/coverages/{coverageid} -- returns a specific coverage (see format encoding for ways to retrieve in specific formats)

**Comment by cportele** [comment]
@KathiSchleidt This discussion (and https://github.com/opengeospatial/ogc_api_coverages/issues/25) is about a collection of features that could also be seen/accessed as a coverage. In that case there is a single coverage. 

If you have a collection of coverages then you will have the resources identified in your comment.

**Comment by KathiSchleidt** [comment]
@cportele thanks for the clarification!
Is it all just a question of plurals here? collection&coverage vs. collections&coverages implying the difference between the following definitions:
WFS_FES:

> /collection/{collectionId}/coverage would be that coverage resource. (pertaining to the collection of features)

OGC API Coverage:

> /collections/{collectionid}/coverages -- returns a list of all coverage identifiers included in a specific collection

**Comment by dblodgett-usgs** [comment]
@cportele -- ok. makes perfect sense that `/collection/{collectionId}/coverage` becomes the purview of OGC-API Coverages. 

In the case of a feature coverage, you may have multiple attributes you might want to access _as a coverage_ or _as a feature_. I really think this is the break down in all this. Data are never _a coverage_ or _a feature collection_ they are always accessed _as a coverage_ or _as a feature collection_. Clearly, some data can only be accessed as one or the other in practice, **but the distinction is a false dichotomy.** 

Coming back to the point here.

`/collections/{collectionId}/coverages` would return all the coverages available from the given collection. In the case the collection is also a feature collection, those coverages would be one or more feature-attributes that are accessible _as a coverage_.

**Comment by joanma747** [comment]
I agree with @cportele here:

Features are too atomic and need to be aggregated in collections for convenience: e.g. to cover a particular extent. Coverages are already an aggregation of data into a coverage structure: a boxel, a point cloud etc. They also have several "attributtes" represented by "rangeTypes" like features.

To me "coverage" is equivalent to "items". They both cover an extent, represent several attributes and can be queried. It is possible to move from items to a coverage by rasterization and for a coverage to items by vectorization.

If OGC API Coverages needs collections of collections is a complete different discussion that also affects features and should be solved in OGC API Common.

**Comment by KathiSchleidt** [comment]
but - is it now collection or collection**s**?

In the above coverage (singular) is paired with collection (singular), coverages (plural) with collections (plural). I don't understand if this is a sloppy artifact (always a bit of an issue when both singular and plural are used as semantically required), or if I'm missing part of the logic. 

To my view, it should be collections (plural) in both cases (as it's followed by a {collectionId}, thus implying multiple members)

**Comment by dblodgett-usgs** [comment]
I'm pretty sure `collection` is just me and others being sloppy? It's [`collections` in the OGC API spec.](http://docs.opengeospatial.org/DRAFTS/17-069r3.html#_collections_)

**Comment by joanma747** [comment]
In my opinion it should be 
/collections/{collectionId}/coverage
in addition to what we know for a long time:
/collections/{collectionId}/items

**Comment by cportele** [comment]
> Is it all just a question of plurals here?

No, it is about the resources. Plural / singular just depends on the nature of the resource(s).

> WFS_FES: /collection/{collectionId}/coverage would be that coverage resource. (pertaining to the collection of features)

You have a misunderstanding about OGC API. The WFS_FES / Features SWG will not/never define requirements for resources like /collection/{collectionId}/coverage. This is just a discussion how a coverage view of a collection of features could potentially be represented in a Web API.

**Comment by cportele** [comment]
> but - is it now collection or collections?

At least in Features it is "collections". See also https://github.com/opengeospatial/OGC-Web-API-Guidelines#principle-4--construct-consistent-uris.

**Comment by lieberjosh** [comment]
There has for a long time been a gap within OWS about connecting different feature resources to the same real-world features. The classic example is a data resource and a map resource, where most services make an implicit and totally un-specified assumption that  the same feature name / id gets the same feature as a different resource. 

This would be a great discussion to have in Banff, but needs to include the very real differences between some of these feature resource types. For example, a collection of features can indeed be thought of as a discrete coverage, but not only are the relevant query parameters different (domain variables vs properties), the entire nature of a coverage is different. A collection of features typically implies that their properties are only defined for the extent of each feature. A coverage implies there is a continuous field of properties being approximated by the coverage cells / members. So one may not be an equivalent resource representation to the other. An easy but correct equivalence within OGC API would be good to work out, but should probably be within the context of a general model for accessing different feature resources for the same or different real-world features within the same overall API.

**Comment by cportele** [comment]
We discussed this in the WFS SWG call today. The consensus was that this is an important topic for OGC API. However, it is not about features, but how we deal with relationships between OGC API resources in general. 

We decided that the discussion should continue in Common and I have created an issue there, see https://github.com/opengeospatial/oapi_common/issues/39.
