### ISSUE TITLE
More communication forums

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/WFS_FES#26]
It'd be great to link to a couple more communication forums in the readme, where people can ask questions, etc. 

* Email - I think the SWG list is closed? There seems to be an old, not used public list - https://lists.opengeospatial.org/mailman/listinfo/wfs-dev Should we revive that and make it a public discussion list? Or make a new public one? In general github issues is where people will likely communicate most things, but having an email list can be more welcoming.

* Chat - I'm liking http://gitter.im recently - great github integration. Could also use slack. For this to work we'd probably need at least either Clemens or Peter to occasionally pop in.

I'd be happy to help create the chat channel.

**Comment by ogcscotts** [comment]
We could open the WFS-FES.SWG list to the public.

**Comment by cholmes** [comment]
Yeah, that would definitely work.

**Comment by pvretano** [comment]
Opening up the SWG list is fine with me.  I can't speak for Clemens but gitter.im and slack would be good too.  The more participation/communication channels the better if you ask me!

**Comment by cholmes** [comment]
Cool. I'd say we pick one of slack vs gitter, so people don't have to monitor both. I'm inclined for gitter, unless someone feels strongly about slack. 

I can set it up later this week.

**Comment by cportele** [comment]
Opening up the SWG list is fine with me, too. I assume this will require a SWG vote?

I have not used Gitter before, but we can give it a try. The integration with GitHub could be plus.

I am not sure about "the more channels the better" as it may result in parallel discussions in different channels, but having something between email and GitHub issues/PRs sounds reasonable.

**Comment by ogcscotts** [comment]
we won't need a SWG vote as the SWG already approved working in the open. This is a formality for the chair... and I've already started the process!

**Comment by cportele** [comment]
@ogcscotts - very good!

**Comment by ogcscotts** [comment]
WFS-FES.SWG@lists.opengeospatial.org is now public

**Comment by cholmes** [comment]
Great. Just created https://gitter.im/opengeospatial/WFS_FES

Scott - others in OGC github org I believe should be able to easily create their own channels. I used the 'opengeospatial' github repo as the 'base', and it has a default 'lobby', and then I created the WFS_FES channel.

**Comment by ogcscotts** [comment]
Excellent - thanks, Chris!

**Comment by cportele** [comment]
Resolved by #28
