### ISSUE TITLE
Move Annex B to the release notes?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#3]
Annex B is meant as a discussion / explanation to the community that uses WFS today. Maybe we should remove this from the document and make it a separate document (part of the release notes)?

**Comment by cmheazel** [comment]
See Issue #4

**Comment by cportele** [comment]
Agreement on 2018-02-01: Will move to the Guide. We need to add a link (or for now mention that there will be a guide). Move some text to the introduction.
