### ISSUE TITLE
Features without a collection

### ISSUE THREAD

**Issue by jvanulde** [opengeospatial/WFS_FES#30]
Just being a devil's advocate here, but is it possible that we may have a feature without a collection? I am looking at #18... I imagine that a "dataset" could be any arbitrary "collection" of web resources (i.e. "spatial things" aka "features"). For example, a dataset could contain references to "features" that exist in zero or many collections, and while that may be a collection unto itself, it isn't necessarily so.

**Comment by cportele** [comment]
I see the point. The idea was to have a simple predictable approach that has a straightforward representation in the API / in URIs.

For example, one problem from an API point of view with features in no collection: How do you get a link to the feature. Currently you get the link via the collection.

**Comment by cmheazel** [comment]
It seem to me that there will always be a root Feature Collection.  The dataset could fill that role.  So then:
1) A dataset is a collection
2) A dataset serves as the root collection for that dataset
3) A Feature Collection is a subclass of collection
4) A dataset serves as the root Feature Collection for that dataset
5) All other Features and Feature Collections form a tree rooted at the dataset Feature Collection.

**Comment by cportele** [comment]
Discussion on 2018-02-01: Leave as it is for now, but wait for developer feedback, if anything needs or should be changed. The Guide can also add discussion about the design decision.

**Comment by cportele** [comment]
13-MAY-2019 conference call: So far no feedback has been raised that the mandatory collection is an issue. You could always use a single "default" collection. Extensions can be specified to publish also all features, for example, under a path `/items`. See, for example, the discussion in the Testbed-14 ER: http://docs.opengeospatial.org/per/18-045.html#collections_selection_extension.

**Comment by cportele** [comment]
See also #154 for a discussion about `/items`.

**Comment by cportele** [comment]
Conference call, 3 June 2019: Closing this issue as there was no further discussion. If new aspects are to be considered, the issue can be reopened.
