### ISSUE TITLE
HTTP 1.1 - what is the current RFC?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/WFS_FES#37]
Currently we reference [RFC 2616](https://tools.ietf.org/rfc/rfc2616.txt). It has no marking as being obsolete, so I assume this is still the HTTP 1.1 specification.

However, since references to the 723x RFCs came up in discussions, I wanted to raise this to see, if am wrong. There is a revision of the HTTP 1.1 spec, split into multiple RFCs (7230 to 7235). According to http://www.rfc-editor.org/info/rfc7231 that RFC is not approved and still a "proposed standard". This is the early phase in IETF, even before it is called a "draft standard". The version is from 2014, so no idea what its status in IETF really is, but my conclusion was/is that RFC 2616 is and will continue to be the HTTP 1.1 spec for some time.

Or am I wrong?

**Comment by pvretano** [comment]
Clemens, my read is the same as yours.  That is to say that RFC 2616 will be the HTTP 1.1 specification for some time to come.

**Comment by cportele** [comment]
Good. Let's keep this issue open for 1-2 weeks to see, if there is any other input.

**Comment by cmheazel** [comment]
https://tools.ietf.org/html/rfc2616 indicates that RFC 2616 has been obsoleted by RFC 7230, 31, 32, 33, 34,and 35.  The 723* RFCs are identified as Proposed Standards and 2616 is a Draft Standard.  I'm not sure if that makes any difference.  

The 7230 series provides more detail than 2616 and makes a few updates and corrections.  However, citing six RFCs when all you want to say is HTTP 1.1 is cumbersome.  Perhaps we could cite 2616 in most cases and only cite the 7230 series RFCs when they differ from 2616.

**Comment by cmheazel** [comment]
Perhaps a few words along these lines:
The HTTP 1.1 specification is under revision.  The existing RFC 2616 standard is being split into multiple RFCs (7230 to 7235).  At this time, those RFCs have not been approved and are still "proposed standards".  However, they do contain additions and changes which impact this specification.  Therefore, the normative HTTP standard for this specification shall be RFC 2616.  However, RFCs from the 7230 series may be cited where they provide clarity or direction which is missing or incorrect in RFC 2616.

**Comment by pvretano** [comment]
12-FEB-2018 teleconference: Reference 2616 in the normative references but if we need to point to specific things, then use the 723* series of documents in those cases.

**Comment by cportele** [comment]
Since we already reference RFC 2616 in the normative reference, this requires no change and we can close this issue. If not and more discussion is required, please reopen it again.
