### ISSUE TITLE
Add contributor IPR statement to Readme

### ISSUE THREAD

**Issue by ogcscotts** [opengeospatial/WFS_FES#52]
We should add a brief note on contribution to the standard as was done with GeoPackage:

"Contributing
The contributor understands that any contributions, if accepted by the OGC Membership, shall be incorporated into the formal OGC GeoPackage standards document and that all copyright and intellectual property shall be vested to the OGC.

The GeoPackage Standards Working Group (SWG) is the group at OGC responsible for the stewardship of the standard, but is working to do as much GeoPackage work in public as possible."

**Comment by cportele** [comment]
Like this?

https://github.com/opengeospatial/WFS_FES/blob/issue-52/README.md#contributing
