### ISSUE TITLE
Lack of standardization for collection metadata response with application/xml media type

### ISSUE THREAD

**Issue by rouault** [opengeospatial/WFS_FES#58]
As far as I can see in the spec, there's no XML schema defined for the collection metadata response with application/xml metadata type

For example,
$ curl -s  -H "Accept: application/xml" "https://www.ldproxy.nrw.de/kataster" | xmllint --format -

returns
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<wfs:Collections xmlns:wfs="http://www.opengis.net/wfs/3.0">
  <wfs:Collection>
    <wfs:name>flurstueck</wfs:name>
    <wfs:title>Flurstück</wfs:title>
    <wfs:extent>
      <wfs:bbox>5.61272621360749</wfs:bbox>
      <wfs:bbox>50.2373512077239</wfs:bbox>
      <wfs:bbox>9.58963433710139</wfs:bbox>
      <wfs:bbox>52.5286304537795</wfs:bbox>
    </wfs:extent>
  </wfs:Collection>
  <wfs:Collection>
    <wfs:name>gebaeudebauwerk</wfs:name>
    <wfs:title>Gebäude, Bauwerk</wfs:title>
    <wfs:extent>
      <wfs:bbox>5.61272621360749</wfs:bbox>
      <wfs:bbox>50.2373512077239</wfs:bbox>
      <wfs:bbox>9.58963433710139</wfs:bbox>
      <wfs:bbox>52.5286304537795</wfs:bbox>
    </wfs:extent>
  </wfs:Collection>
  <wfs:Collection>
    <wfs:name>verwaltungseinheit</wfs:name>
    <wfs:title>Verwaltungseinheit</wfs:title>
    <wfs:extent>
      <wfs:bbox>5.61272621360749</wfs:bbox>
      <wfs:bbox>50.2373512077239</wfs:bbox>
      <wfs:bbox>9.58963433710139</wfs:bbox>
      <wfs:bbox>52.5286304537795</wfs:bbox>
    </wfs:extent>
  </wfs:Collection>
</wfs:Collections>
```

but it is not immediately obvious that this is howl https://github.com/opengeospatial/WFS_FES/blob/master/core/openapi/schemas/content.yaml should be encoded in XML

**Comment by cportele** [comment]
Yes, this is a weak area. Originally we had XML annotations in the OpenAPI fragments ([link](https://github.com/opengeospatial/WFS_FES/blob/899b98cfa7f6231ccee7b1cdc5538c23a76a0a2b/core/openapi/schemas/content.yaml)), but removed them because the way OpenAPI currently supports XML is kind of messy and likely to change (based on some discussions in the OpenAPI issues). I guess you are right and we should specify an explicit XML schema for the resource, when XML is used.

**Comment by pvretano** [comment]
I generated a schema for this at http://www.pvretano.com/schemas/wfs/3.0/wfs.xsd
Some caveats:
1. I created this file by copying the 2.5 schema and migrating it to 3.0.  Most of it is not applicable but I figure over time I can prune the file to get rid of the stuff we no longer use.
2. I really did not like the use of the wfs:extent and wfs:box elements so I used the ows:WGS84BoundingBox element instead.  If the goal is to break any dependency with OWS Common that I think we should pull the WGS84BoundingBox element into the WFS 3.0 namespace thus breaking the dependency.

Another option might be to look at how ATOMPUB defines collection and extend slightly for spatial.

**Comment by cportele** [comment]
Discussion in web-meeting 2018-03-12: Include schema for XML in first draft release.

**Comment by cportele** [comment]
Work in progress: http://pvretano.com/schemas/wfs/3.0/wfs.xsd

**Comment by cportele** [comment]
Discussion on 2018-03-27: The schema should be available in a few days.
