### ISSUE TITLE
Unsufficiently specified format for crs values

### ISSUE THREAD

**Issue by rouault** [opengeospatial/WFS_FES#59]
From https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/collectionInfo.yaml , one can guess that the format for crs values is OGC URLs, but would be good to mention it if that's the case. The reference is probably "OGC CRS Name Type Definition" [OGC 11-135] / https://portal.opengeospatial.org/files/?artifact_id=46361

**Comment by cportele** [comment]
So far, crs is mainly a placeholder for future use in extensions (there is also a note in the text) as the Core is restricted to WGS84 lon/lat. This is the reason why this is not discussed in more detail as there are currently no requirements related to CRSs. But I guess it can be confusing as it is. Either drop it from the Core and only add it in extensions or provide more guidance.

**Comment by aaime** [comment]
The specification could use a prominent statement (a dedicated section maybe?) that everything must be in CRS84 though. The only statement I could find is in Example 3, there it's easily overlooked imho: "Coordinate reference system information is not provided as the service provides geometries only in the default system (WGS84 longitude/latitude)."

**Comment by cportele** [comment]
@aaime You are right, I thought we had a normative statement about this somewhere, but obviously not. This needs to be fixed.
