### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jvanulde** [opengeospatial/WFS_FES#6]
Does there need to be any discussion around secure channel (e.g. HTTPS) vs HTTP? How about protocol-relative URI's? I understand that it's an anti-pattern. A best practice might be warranted.

**Comment by jvanulde** [comment]
Sorry, just saw the reference in section 5.4. Again, though a best practice statement at minimum might be warranted.

**Comment by cportele** [comment]
What kind of best practice statement do you have in mind? Could you make a proposal that we could discuss?

**Comment by jvanulde** [comment]
@cportele Was thinking of something along the lines of https://https.cio.gov/

**Comment by cportele** [comment]
Discussed during the meeting on 2017-11-28: The current text seems sufficient for now. If we identify in the period where we will work on implementations of the specification that more guidance is needed (e.g., on redirects from http to https), we will add it.
