### ISSUE TITLE
Inconsistency collectionId vs name

### ISSUE THREAD

**Issue by rouault** [opengeospatial/WFS_FES#61]
https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html (below Requirement 10) has an inlined outdated version of https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/collectionInfo.yaml that uses a "collectionId" instead of "name" in the .yaml file. The "Example 3. Feature collection metadata response document" is also erroneous

**Comment by cportele** [comment]
Thanks - yes, that needs to be fixed.

**Comment by cportele** [comment]
resolved as part of pull request #70
