### ISSUE TITLE
"Example 3. Feature collection metadata response document" not consistent with /req/core/fc-md-links : item vs about

### ISSUE THREAD

**Issue by rouault** [opengeospatial/WFS_FES#62]
Requirement 9 /req/core/fc-md-links mentions that the link array "SHALL include an item for each supported encoding with a link to the collection resource (relation: item)." but example 3 seems to use "rel": "about" for that purpose.
https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/collectionInfo.yaml does use rel: item in the example.

**Comment by cportele** [comment]
Thanks, it should be "item". This is already included in PR #70.

**Comment by cportele** [comment]
resolved as part of pull request #70
