### ISSUE TITLE
Clarification on features being part of exactly one collection

### ISSUE THREAD

**Issue by konradkorczynski** [opengeospatial/WFS_FES#66]
During WFS 3.0 hackathon a question was raised about the below.

Section 7.1 of OGC Web Feature Service 3.0 - Part 1: Core specifies the following:
Each Collection consists of the features in the collection where each feature in the distribution is part of exactly one collection.

Can more clarification please be given on this point?

It might seem the statement tries to imply how data supporting the WFS implementation is to be organised, which might sound unnecessary.

Although it makes perfect sense, some data models might require different approach. An example of a feature belonging to more than one collection was given during the event e.g.:
- a feature of id: 7 can be part of collections:
-- buildings
-- skyscrapers
The above example also sparked conversations on how to deal with transactions of such features (if building id: 7 is changed, the skyscraper id: 7 should be changed as well logically).

Is therefore the statement a 'best practice' possibly?

**Comment by cportele** [comment]
For now, I have added a link in the document from that statement to the issue.

I do not think that we have to resolve this necessarily now, but we need to clarify the concepts before we finalize the Core.

**Comment by cportele** [comment]
15-April-2019 Teleconference: The same real-world entity could have features in multiple collections, but in the WFS 3.0 Core the only identifier of a feature that is specified is the URI, so multiple instances would have different URIs and as a result would "look" like multiple features. If an external authority-assigned identifier would exist, a client could determine that the two features actually represent the same real-world entity. However, that is out-of-scope for the Core. Clemens will check the wording in the draft spec and close the issue afterwards.

**Comment by cportele** [comment]
Closing this after review of the text.
