### ISSUE TITLE
Links property for response at path `/` is optional?

### ISSUE THREAD

**Issue by ahmedOpeyemi** [opengeospatial/WFS_FES#69]
The schema defined on [the spec document](https://rawgit.com/opengeospatial/WFS_FES/master/docs/17-069.html#_response) as response to a GET request on the `/` path shows the property `links` to be optional. However in the reference [yaml document](https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/content.yaml) that contains the schema, it is marked required.

**Comment by cportele** [comment]
Thanks, @ahmedOpeyemi. Since `/req/core/fc-md-links` requires that links are provided, the document was wrong. This has been fixed  in pull request #70.

**Comment by cportele** [comment]
resolved as part of pull request #70
