### ISSUE TITLE
Projected GeoJSON

### ISSUE THREAD

**Issue by geekdenz** [opengeospatial/WFS_FES#71]
I had a question for Peter @ CubeWerx:

Is it just a recommendation for GeoJSON to just support WGS84 or would it make sense to have an optional projection on the server to say EPSG:3857? I got the impression that different vendors actually implement this.

This may make it easier for clients to parse the GeoJSON, not having to reproject and also avoid double reprojection. The server may have to reproject if the data is in another projection and then the client has to project again. I would have thought the projection code could be in the response JSON and/or one could specify in the request what projections one would accept.

Peter may have more input on this.

**Comment by cportele** [comment]
Thanks @geekdenz 

Is this a duplicate of #65?

**Comment by geekdenz** [comment]
@cportele Yes, thank you.
