### ISSUE TITLE
Transactional WFS recommendations

### ISSUE THREAD

**Issue by perrygeo** [opengeospatial/WFS_FES#72]
The current core includes requirements for handling GET requests. Based on conversation at the Hackathon, it seemed that transactional parts of WFS should exist as an extension.

But the abstract starts off with

> The Web Feature Service (WFS) offers the capability to create, modify and query spatial data on the Web.

Should we clarify up front that WFS 3.0 core is query only?

And should the spec also make recommendations for handling PUT, POST, PATCH and DELETE methods? Say explicitly that the core specifies only how GET requests should be handled, the rest are up to extensions.

**Comment by cportele** [comment]
Thanks, @perrygeo . That makes sense to me, I will give it a try to update the abstract accordingly.
