### ISSUE TITLE
Quick links in specification ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/WFS_FES#77]
Is possible to have a section or table or something in the document that summarizes the access paths for the WFS and links to the relevant sections in the document?  I actually imagine a table where the first column is the access path (i.e. /, /api, /conformance, /collections, /collections/{name}, /collections/{name}/items, etc.) and then another column with a set of relevant links into the specification so you can zoom right to path you are interested in.  We might also think about three columns with the HTTP methods too.  I have attached an image with a mock up of what I have in mind
![path_toc](https://user-images.githubusercontent.com/4433459/37171264-47311e86-22db-11e8-93dd-ca388fce1ffb.png)

**Comment by cportele** [comment]
I will include this at the end of the Abstract.
