### ISSUE TITLE
Heterogenous Feature[Type]Collections

### ISSUE THREAD

**Issue by mclay** [opengeospatial/WFS_FES#80]
in WFS 2.x (and other GML derivatives like AIXM) there is this concept of [Simple]FeatureCollection that allows to capture multiple Features of __different__ Feature __types__ into one collection with or without __local references__ between them by means of gml:id and xlink. 

My question is will this concept be considered/retained in WFS 3.0 and if yes how does it map to currently envisioned REST style semantics of having a 1:1 relation between resource and Feature type.
  

![simplefeaturecollection](https://user-images.githubusercontent.com/393727/37216573-67e765fa-23bb-11e8-9c3e-aa43ca24e8e4.PNG)

**Comment by cportele** [comment]
There is no requirement in WFS 3.0 Core that the members of a feature collection have to be of the same feature type. In fact, the concept of feature types is not important in the Core. How the features in the dataset are aggregated into collections is entirely the decision of the provider. There is also no requirement (in the Core) to have a schema or feature types.

However, in the Core you will only be able to retrieve the features of a single collection in one request. It is planned to specify an extension for a richer search capability in another part. This is expected to support retrieving features from multiple collections in one response.

PS: The following is not accurate:

> having a 1:1 relation between resource and Feature type.

WFS 3.0 makes no assumption about this, which is important. While every feature belongs to exactly one feature type in GML, GeoJSON has no concept of feature types and in GeoSPARQL a feature may have multiple feature types.

**Comment by mclay** [comment]
hi @cportele ,

many thanks for the clarification - one last question to that before i close this question as answered. What would be the related concept in WFS-3.0 for the following WFS-2.0 Insert operation. Especially i am interested in the designated or compliant (feature collection?) path for ingesting multiple heterogenous  features at once.

```
<wfs:Transaction>
    <wfs:Insert>
		<Feature_of_type_A/>
		
		<Feature_of_type_B gml:id="FeatureB_1"/>
		
		<Feature_of_type_C>
			<reference_Property xlink:href="FeatureB_1"/>
		</Feature_of_type_C>
		
   </wfs:Insert>
</wfs:Transaction>
```

**Comment by cportele** [comment]
Hi @mclay,

in previous discussions the idea was to support two approaches for inserting, updating, deleting features in a WFS REST binding:

* A simple transaction capability to create, modify and delete individual features. I.e. POST a feature to a collection or DELETE, PUT, PATCH an existing feature.
* A complex transaction capability that supports the transactions as described in your comment and provides the ability to create, modify and/or delete multiple features of one or more types in one request. I.e. POST a transaction to a `/transaction` (or similar) resource. 

So far, the plan in discussions has always been to support both options in WFS 3.0 extensions. The first option is easier and will likely be specified earlier than the second option. One aspect that we need to specify in the second case is which feature is inserted into which collection (as there is no requirement to aggregate collections by feature type in WFS 3.0).

**Comment by mclay** [comment]
@cportele thanks for clarification i will close this as answered
