### ISSUE TITLE
Remove the word "collection" from the definition of "dataset" to avoid confusing these terms.

### ISSUE THREAD

**Issue by JivanAmara** [opengeospatial/WFS_FES#86]
4.1 "dataset" indicates all of the data served up by an entity.  Using the word "collection" in this definition confuses this with the use of "collection" to refer to sub-groupings of the dataset into feature collections.

**Comment by cportele** [comment]
I see the point, but we should avoid changing the definition as it is from DCAT. 

Maybe add a note under the definition instead that clarifies the different uses of collection?

**Comment by cportele** [comment]
Discussion 2018-03-27: add definition of collection as synonym for feature collection. Add note under dataset definition to clarify that the use of "collection" in the DCAT definition is broader than the use of collection in this specification.
