### ISSUE TITLE
Boolean value in scalarExpression

### ISSUE THREAD

**Issue by Diaaz** [opengeospatial/WFS_FES#862]
Hi,

I am trying to implement deserializing a json filter with a boolean value. In schema/cql2.json this is a binaryComparisonPredicate, with (in example below) op '<>' and two scalarExpressions as args. In the schema scalarExpression is one of character-, numeric, cql2- or temporalInstant-Expression. I cannot find boolean in those types. Am I missing something? ScalarLiteral seems to have a reference to boolean, but that type is not used.

The sample I am trying to implement is example69.json:
```
{
  "op": "<>",
  "args": [
    false,
    {
      "function": {
        "name": "Bar",
        "args": [ { "property": "geometry" }, 100, "a", "b", false ]
      }
    }
  ]
}
```

Kind regards.

**Comment by pvretano** [comment]
@Diaaz I took a look at cql2.json `scalarExpression` is defined as 
````
"scalarExpression": {
      "oneOf": [
        {
          "$ref": "#/$defs/characterExpression"
        },
        {
          "$ref": "#/$defs/numericExpression"
        },
        {
          "$dynamicRef": "#cql2expression"
        },
        {
          "$ref": "#/$defs/temporalInstantExpression"
        }
      ]
    },
````
The `$dynamicRef` is the boolean expression in the definition of a scalar expression.  It's basically saying a scalar expression can be any expression that evaluates to a boolean including a literal boolean (`true` or `false`). 

Does this answer your question?

**Comment by pvretano** [comment]
@Diaaz I hope I have interpreted your question correctly and I am answering what you are asking ...

OK ... all CQL2 expressions resolve to a `true` or `false` value indicating whether the thing the predicate is testing should be part of a query result set or not.  

Boolean expressions can be literal boolean values `true` or `false` OR they can be some expression (e.g. `10 > 2`) that itself resolves to a boolean.  Furthermore, the grammer supports logically connecting expressions using `AND`, `OR` and `NOT` to form longer expression that in true resolve to a `true` or `false` value.  

The `oneOf[]` is there to account for all the ways that an expression that resolves to a boolean `true` or `false` can be formed within the CQL2 grammar.

Does that answer your question?
