### ISSUE TITLE
Confusing crs84 requirement

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/WFS_FES#92]
The requirement ```/req/core/crs84``` is mentions the possibility for users to use other CRS than crs84.

> Unless the client explicitly requests a different coordinate reference system, all spatial geometries SHALL be in the coordinate reference system http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS84 longitude/latitude).

It should be made clear that the Core only supports CRS84 for both the provided geometries and user provided operation parameters.

This issue is related to #65

**Comment by cportele** [comment]
The statement after the requirement makes this clear:

> The Core does not specify a capability to request geometries in a different coordinate reference system. Such a capability will be specified in another part of the WFS 3.0 series.

Does the wording need to be improved? If yes, do you have a proposal?

This statement does not belong into the requirement itself as the requirement is intended to apply for any extension, too.

**Comment by ilkkarinne** [comment]
I have a pull request coming up
